//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGate_Global_3D_Secure_Enterprise_Example.ccPayments {
    
    
    public partial class ActionThree {
    }
}
