
package com.mygateglobal.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsAPIService", targetNamespace = "https://api.mygateglobal.com/", wsdlLocation = "https://api.mygateglobal.com/api/api.wsdl")
public class WsAPIService
    extends Service
{

    private final static URL WSAPISERVICE_WSDL_LOCATION;
    private final static WebServiceException WSAPISERVICE_EXCEPTION;
    private final static QName WSAPISERVICE_QNAME = new QName("https://api.mygateglobal.com/", "wsAPIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.mygateglobal.com/api/api.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSAPISERVICE_WSDL_LOCATION = url;
        WSAPISERVICE_EXCEPTION = e;
    }

    public WsAPIService() {
        super(__getWsdlLocation(), WSAPISERVICE_QNAME);
    }

    public WsAPIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSAPISERVICE_QNAME, features);
    }

    public WsAPIService(URL wsdlLocation) {
        super(wsdlLocation, WSAPISERVICE_QNAME);
    }

    public WsAPIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSAPISERVICE_QNAME, features);
    }

    public WsAPIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsAPIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns APIService
     */
    @WebEndpoint(name = "APIPort")
    public APIService getAPIPort() {
        return super.getPort(new QName("https://api.mygateglobal.com/", "APIPort"), APIService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns APIService
     */
    @WebEndpoint(name = "APIPort")
    public APIService getAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://api.mygateglobal.com/", "APIPort"), APIService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSAPISERVICE_EXCEPTION!= null) {
            throw WSAPISERVICE_EXCEPTION;
        }
        return WSAPISERVICE_WSDL_LOCATION;
    }

}
