//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGateGlobalVisa3DSIntergration.ThreeDSecure_15 {
    
    
    public partial class ThreeDSecure_15 {
    }
}
